### ISSUE TITLE
Issues discussed on Gitter

### ISSUE THREAD

**Issue by Paebbels** [buildthedocs/btd#2]
For now, we have:

* [x] buildthedocs/sphinx_btd_theme#1: Change text justification rules to `justified` - default of HTML is `ragged-right`
* [x] buildthedocs/sphinx_btd_theme#2: Add the documentation title above the search box as in the original RTFD theme.
    The space consuming part is the branch name - this can be omitted. 
* [x] buildthedocs/sphinx_btd_theme#3: Some menu items are hidden by the download box in the bottom corner.
* [x] buildthedocs/sphinx_btd_theme#4: The versions box should remember the collapsed/expanded state when changing to a different page. The default should be collapsed - first visit.
---
* [x] The Repo, View and Edit links in the top-right are missing some elements in the path (the repo name). (fixed in https://github.com/buildthedocs/btd/commit/9d923e74d0bd52fe749eb8cc8409a97ecf67c378)
* [x] The Download PDF in the versions box points to an non-existing file.
* [x] The Download HTML (tarball) in the versions box points to an non-existing file. (fixed in https://github.com/buildthedocs/btd/commit/3efe31d4438d5263a25506983e8f46f430c1b785)

**Comment by eine** [comment]
See https://github.com/buildthedocs/sphinx.theme/issues/4#issuecomment-657154686
